trigger:
- main
- test

variables:
- group: smart-app

stages:
- template: './devops/plantillas/ci-cd/stages/cicd-stages.yaml'
  parameters:
    nodeVersion: 18
    sonarSc: $(sonarSc)
    sonarProjectname: 'prueba-smart'
    dockerSc: $(dockerSc)
    containerRepository: $(containerRepository)
    azureSc: $(azureSc)
    appServiceName: $(appServiceName)
    snykSc: $(snykSc)